name: Uno
version: '1.0-SNAPSHOT'
main: gstech.yao37.uno
author: yao37 # QQ:3212576603
description: This plugin is a minigame plugin called Uno which you can have fun with your friends
api-version: '1.20'
commands:
  forHelp:
    description: the main command of Uno plugin
    usage: /uhelp
    aliases: [uno, unohelp]